# Generated by Django 4.2.4 on 2025-02-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_app', '0004_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
    ]
